"""Add user agent, response time, and geographic data to messages

Revision ID: 18c534904549
Revises: ba279d010bf5
Create Date: 2025-07-20 06:22:45.502155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = '18c534904549'
down_revision: Union[str, None] = 'ba279d010bf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('messages', sa.Column('response_time_ms', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True))
    op.add_column('messages', sa.Column('region', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('messages', sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'city')
    op.drop_column('messages', 'region')
    op.drop_column('messages', 'country')
    op.drop_column('messages', 'response_time_ms')
    op.drop_column('messages', 'user_agent')
    # ### end Alembic commands ###
