"""Add browser_id field to users table

Revision ID: 9ad03f771076
Revises: be509f25455e
Create Date: 2025-07-24 03:15:22.878921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = '9ad03f771076'
down_revision: Union[str, None] = 'be509f25455e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add browser_id column as nullable first
    op.add_column('users', sa.Column('browser_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    
    # Update existing users with a default browser_id (using their username as fallback)
    op.execute("UPDATE users SET browser_id = username WHERE browser_id IS NULL")
    
    # Now make it non-nullable
    op.alter_column('users', 'browser_id', nullable=False)
    
    op.create_index(op.f('ix_users_browser_id'), 'users', ['browser_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_browser_id'), table_name='users')
    op.drop_column('users', 'browser_id')
    # ### end Alembic commands ###
